# Site settings
title: danthedev
baseurl: ""
url: "https://danthedev.com"
email: dan@astraldynamics.co.uk
twitter_handle: workshydev
github_handle: danprince
permalink: "/:year/:month/:day/:title"
image:
  src: "/img/banner.jpg"

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: :compressed
